apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonar-postgres
  template:
    metadata:
      name: sonar-postgres
      labels:
        name: sonar-postgres
    spec:
      containers:
        - image: postgres:16
          name: sonar-postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgressql_pass
            - name: POSTGRES_USER
              value: postgressql_user
            - name: POSTGRES_DB
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 2048m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: .5Gi
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: claim-postgres