kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-postgres
  namespace: sonarqube
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi