kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgres
  namespace: sonarqube
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/admin/Desktop/elkasaby/ITI/sonarqube/demo01/apply-postgressql/sonarqube-postgress"