kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sonarqube-data
  namespace: sonarqube
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/admin/Desktop/elkasaby/ITI/sonarqube/demo02/apply-sonarqube/sonarqube-data"